name: Third Party License Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  licenses:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Check Third Party Licenses
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
          cache-disabled: true
          arguments: clean checkLicense
