name: Third Party License Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  licenses:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Check Third Party Licenses
        run: ./gradlew clean checkLicense
