name: Third Party License Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  licenses:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Third Party Licenses
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
          cache-disabled: false
          arguments: checkLicense
      - name: Print Without Licenses File
        if: always()
        run: cat ./build/licenses/dependencies-without-allowed-license.json
